"use client"

// Used for making HTTP requests to the API
import axios from "axios";

// zod: A schema validation library to validate  data structures
import * as z from "zod"
import { Code, Loader } from "lucide-react";
import { useForm } from "react-hook-form"

// Custom UI components: Heading for page titles, UserAvatar and BotAvatar for user and bot representations in chats,
// Empty for empty state messages, and Loading for indicating loading states.
import Heading from "@/components/heading";
import { Empty } from "@/components/empty";
import { Loading } from "@/components/loading";
import { UserAvatar } from "@/components/user-avatar";
import { BotAvatar } from "@/components/bot-avatar";

// Schema for form validation using zod
import { formSchema } from "./constants";

import { useRouter } from "next/navigation"

// Using zod to create the schema and validation
import { zodResolver } from "@hookform/resolvers/zod"
//Shadcn components and packages;
import { Form, FormControl, FormField, FormItem } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

import { useState } from "react";
import { cn } from "@/lib/utils";

// interface from the OpenAI package used to define the structure of chat messages
import  {ChatCompletionRequestMessage}  from "openai"

// Component used to display the code generated by the AI in an elegant manner
import ReactMarkdown from "react-markdown"

// custom hook for managing the modal related to the pro features of the app
import { useProModal } from "@/hooks/use-pro-modal";

// used for user feedback like success or error messages
import toast from "react-hot-toast";

const CodePage = () => {
      // Hook for modal and routing
    const proModal = useProModal()
    const router = useRouter()

    // State for managing messages in the conversation
    const [messages, setMessages] = useState<ChatCompletionRequestMessage[]>([])

    // Setup form with react-hook-form and zod for validation
    const form = useForm<z.infer<typeof formSchema>>({
        resolver: zodResolver(formSchema),
        defaultValues: {
            prompt: ""
        }
    })

    // Flag for submission state
    const isLoading = form.formState.isSubmitting

     // Handling form submission
    const onSubmit = async ( values:z.infer<typeof formSchema>) =>{
        try{

        
          const userMessage: ChatCompletionRequestMessage = { role: "user", content: values.prompt };

          const newMessages = [...messages, userMessage]

          const response = await axios.post("/api/code", {
            messages: newMessages
          })

          setMessages((current) => [...current, userMessage, response.data])

          form.reset()


        } catch (error: any){
              if(error?.response?.status === 403){
                proModal.onOpen()
           }else {
             toast.error("Something went wrong")
           }
            console.log(error)
        } finally{
            router.refresh()
        }
        
    }
     // Rendering the code page
    return ( 
        <div>
           <Heading
            title = "Code Generation"
            description = "Generate code using descriptive text"
            icon = { Code}
            iconColor = "text-green-700"
            bgColor = "bg-green-700/10 "
             />
            <div className="px-4 lg:px-8">

                <div>
                    <Form {...form}>
                        <form onSubmit={form.handleSubmit(onSubmit)}
                            className="rounded-lg border w-full p-4 px-3 md:px-6 focus-within:shadow-sm grid grid-cols-12 gap-2">
                            
                            <FormField 
                                 name = "prompt"
                                 render={({field}) =>(
                                    <FormItem className="col-span-12 lg:col-span-10">
                                        <FormControl className="m-0 p-0">
                                          <Input
                                            className="border-0 outline-none
                                            focus-visible:ring-0
                                            focus-visible:ring-transparent"
                                            disabled ={isLoading}
                                            placeholder="Simple toggle button using react hooks"
                                            {...field}
                                            />
                                      </FormControl>
                                    </FormItem>
                                 )}/>
                                 <Button className = "col-span-12 lg:col-span-2 w-full"
                                    disabled={isLoading}>
                                    Generate
                                    </Button>
                        </form>
                    </Form>
                </div>
                <div className="space-y-4 mt-4">
                     {/* Display a loading indicator when a request is in progress */}
                    {isLoading && (
                        <div className="p-8 rounded-lg w-full flex items-center
                            justify-center bg-muted">
                                <Loading/>

                        </div>
                    )}
                      {/* Display a message if no conversation has started yet */}
                    {messages.length === 0 && !isLoading && (
                        <Empty label=" No conversation started"/>
                    )}
                     {/* Render the conversation messages */}
                    <div className="flex flex-col-reverse gap-y-4">
                        {messages.map((message)=>(
                            <div key = {message.content}
                             className={cn(
                                "p-8 w-full flex items-start gap-x-8 rounded-lg",
                                message.role === "user" ? "bg-white border border-black/10" : "bg-muted"
                             )}
                            >
                                 {/* Display user or bot avatar depending on the message role */}
                                {message.role === "user" ? <UserAvatar/> : 
                                <BotAvatar /> }

                                 {/* Display the code written by the bot in an unique manner */}
                              <ReactMarkdown
                                components={{
                                    // Customizing the <pre> tag for code blocks
                                    pre: ({node, ...props}) => (
                                        <div className="overflow-auto w-full my-2 bg-black/10 p-2 rounded-lg ">
                                                <pre {...props} />
                                         </div>
                                    ),
                                    // Customizing the <code> tag for inline code
                                    code: ({node, ...props}) => (
                                        <code className="bg-black/10 rounded-lg p-1" {...props} />
                                    )
                                }}

                                className="text-sm overflow-hidden leading-7"
                              >
                                {message.content || ""}
                              </ReactMarkdown>
                            </div>

                        ))}
                    </div>
                </div>
            </div>
        </div>
     );
}
export default CodePage;